// Writes migrations/0008_seed_catalog.sql from shared/grocery-catalog.ts. Run: npm run catalog
import { writeFileSync } from 'node:fs'
import { GROCERY_CATALOG } from '../shared/grocery-catalog'
import { matchKeys, toKatakana } from '../shared/products'

const q = (s: string) => `'${s.replace(/'/g, "''")}'`
const owner = new Map<string, string>()
const lines = [
  '-- Generated by scripts/gen-catalog-sql.ts from shared/grocery-catalog.ts. Do not edit by hand.',
  `-- ${GROCERY_CATALOG.length} common grocery items and their aliases.`,
  'DELETE FROM catalog_aliases;',
]
GROCERY_CATALOG.forEach((c, i) => {
  const id = i + 1
  lines.push(
    `INSERT INTO catalog (id, name, reading, en, kind) VALUES (${id}, ${q(c.name)}, ${q(c.reading)}, ${q(c.en)}, ${q(c.kind)})
  ON CONFLICT(id) DO UPDATE SET name = excluded.name, reading = excluded.reading, en = excluded.en, kind = excluded.kind;`,
  )
  // A one-kana reading such as す (酢) would match stray OCR text, so short readings are not aliases.
  const spellings = [c.name, ...c.aliases, ...(c.reading.length >= 2 ? [c.reading, toKatakana(c.reading)] : [])]
  for (const key of new Set(spellings.flatMap(matchKeys))) {
    const prev = owner.get(key)
    if (prev && prev !== c.name) throw new Error(`Alias "${key}" belongs to both ${prev} and ${c.name}`)
    if (prev) continue
    owner.set(key, c.name)
    lines.push(`INSERT INTO catalog_aliases (key, catalog_id) VALUES (${q(key)}, ${id});`)
  }
})
writeFileSync(new URL('../migrations/0008_seed_catalog.sql', import.meta.url), lines.join('\n') + '\n')
console.log(`${GROCERY_CATALOG.length} catalog items, ${owner.size} aliases`)
