/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAddRouteImport } from './routes/_app/add'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as ApiTelegramRouteImport } from './routes/api/telegram'
import { Route as AppDayDateRouteImport } from './routes/_app/day.$date'
import { Route as AppExpenseIdRouteImport } from './routes/_app/expense.$id'
import { Route as AppMonthYmRouteImport } from './routes/_app/month.$ym'
import { Route as AppProductIdRouteImport } from './routes/_app/product.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAddRoute = AppAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDayDateRoute = AppDayDateRouteImport.update({
  id: '/day/$date',
  path: '/day/$date',
  getParentRoute: () => AppRoute,
} as any)
const AppExpenseIdRoute = AppExpenseIdRouteImport.update({
  id: '/expense/$id',
  path: '/expense/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppMonthYmRoute = AppMonthYmRouteImport.update({
  id: '/month/$ym',
  path: '/month/$ym',
  getParentRoute: () => AppRoute,
} as any)
const AppProductIdRoute = AppProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/add': typeof AppAddRoute
  '/products': typeof AppProductsRoute
  '/settings': typeof AppSettingsRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/day/$date': typeof AppDayDateRoute
  '/expense/$id': typeof AppExpenseIdRoute
  '/month/$ym': typeof AppMonthYmRoute
  '/product/$id': typeof AppProductIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/add': typeof AppAddRoute
  '/products': typeof AppProductsRoute
  '/settings': typeof AppSettingsRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/': typeof AppIndexRoute
  '/day/$date': typeof AppDayDateRoute
  '/expense/$id': typeof AppExpenseIdRoute
  '/month/$ym': typeof AppMonthYmRoute
  '/product/$id': typeof AppProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/add': typeof AppAddRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/_app/': typeof AppIndexRoute
  '/_app/day/$date': typeof AppDayDateRoute
  '/_app/expense/$id': typeof AppExpenseIdRoute
  '/_app/month/$ym': typeof AppMonthYmRoute
  '/_app/product/$id': typeof AppProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/add'
    | '/products'
    | '/settings'
    | '/api/telegram'
    | '/day/$date'
    | '/expense/$id'
    | '/month/$ym'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/add'
    | '/products'
    | '/settings'
    | '/api/telegram'
    | '/'
    | '/day/$date'
    | '/expense/$id'
    | '/month/$ym'
    | '/product/$id'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_app/add'
    | '/_app/products'
    | '/_app/settings'
    | '/api/telegram'
    | '/_app/'
    | '/_app/day/$date'
    | '/_app/expense/$id'
    | '/_app/month/$ym'
    | '/_app/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiTelegramRoute: typeof ApiTelegramRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/add': {
      id: '/_app/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AppAddRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/day/$date': {
      id: '/_app/day/$date'
      path: '/day/$date'
      fullPath: '/day/$date'
      preLoaderRoute: typeof AppDayDateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expense/$id': {
      id: '/_app/expense/$id'
      path: '/expense/$id'
      fullPath: '/expense/$id'
      preLoaderRoute: typeof AppExpenseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/month/$ym': {
      id: '/_app/month/$ym'
      path: '/month/$ym'
      fullPath: '/month/$ym'
      preLoaderRoute: typeof AppMonthYmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/product/$id': {
      id: '/_app/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof AppProductIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAddRoute: typeof AppAddRoute
  AppProductsRoute: typeof AppProductsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDayDateRoute: typeof AppDayDateRoute
  AppExpenseIdRoute: typeof AppExpenseIdRoute
  AppMonthYmRoute: typeof AppMonthYmRoute
  AppProductIdRoute: typeof AppProductIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddRoute: AppAddRoute,
  AppProductsRoute: AppProductsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppDayDateRoute: AppDayDateRoute,
  AppExpenseIdRoute: AppExpenseIdRoute,
  AppMonthYmRoute: AppMonthYmRoute,
  AppProductIdRoute: AppProductIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiTelegramRoute: ApiTelegramRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
